/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package giros.org;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Labels extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7031988076465615846L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Labels\",\"namespace\":\"giros.org\",\"fields\":[{\"name\":\"label\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Label\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"doc\":\"/metric/labels/label/name\"},{\"name\":\"value\",\"type\":\"string\",\"doc\":\"/metric/labels/label/value\"}],\"aliases\":[\"labelType\"]}}],\"doc\":\"/metric/labels/label\"}],\"aliases\":[\"labelsType\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Labels> ENCODER =
      new BinaryMessageEncoder<Labels>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Labels> DECODER =
      new BinaryMessageDecoder<Labels>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Labels> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Labels> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Labels> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Labels>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Labels to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Labels from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Labels instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Labels fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** /metric/labels/label */
   private java.util.List<giros.org.Label> label;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Labels() {}

  /**
   * All-args constructor.
   * @param label /metric/labels/label
   */
  public Labels(java.util.List<giros.org.Label> label) {
    this.label = label;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return label;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: label = (java.util.List<giros.org.Label>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'label' field.
   * @return /metric/labels/label
   */
  public java.util.List<giros.org.Label> getLabel() {
    return label;
  }


  /**
   * Sets the value of the 'label' field.
   * /metric/labels/label
   * @param value the value to set.
   */
  public void setLabel(java.util.List<giros.org.Label> value) {
    this.label = value;
  }

  /**
   * Creates a new Labels RecordBuilder.
   * @return A new Labels RecordBuilder
   */
  public static giros.org.Labels.Builder newBuilder() {
    return new giros.org.Labels.Builder();
  }

  /**
   * Creates a new Labels RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Labels RecordBuilder
   */
  public static giros.org.Labels.Builder newBuilder(giros.org.Labels.Builder other) {
    if (other == null) {
      return new giros.org.Labels.Builder();
    } else {
      return new giros.org.Labels.Builder(other);
    }
  }

  /**
   * Creates a new Labels RecordBuilder by copying an existing Labels instance.
   * @param other The existing instance to copy.
   * @return A new Labels RecordBuilder
   */
  public static giros.org.Labels.Builder newBuilder(giros.org.Labels other) {
    if (other == null) {
      return new giros.org.Labels.Builder();
    } else {
      return new giros.org.Labels.Builder(other);
    }
  }

  /**
   * RecordBuilder for Labels instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Labels>
    implements org.apache.avro.data.RecordBuilder<Labels> {

    /** /metric/labels/label */
    private java.util.List<giros.org.Label> label;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(giros.org.Labels.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.label)) {
        this.label = data().deepCopy(fields()[0].schema(), other.label);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Labels instance
     * @param other The existing instance to copy.
     */
    private Builder(giros.org.Labels other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.label)) {
        this.label = data().deepCopy(fields()[0].schema(), other.label);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'label' field.
      * /metric/labels/label
      * @return The value.
      */
    public java.util.List<giros.org.Label> getLabel() {
      return label;
    }


    /**
      * Sets the value of the 'label' field.
      * /metric/labels/label
      * @param value The value of 'label'.
      * @return This builder.
      */
    public giros.org.Labels.Builder setLabel(java.util.List<giros.org.Label> value) {
      validate(fields()[0], value);
      this.label = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'label' field has been set.
      * /metric/labels/label
      * @return True if the 'label' field has been set, false otherwise.
      */
    public boolean hasLabel() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'label' field.
      * /metric/labels/label
      * @return This builder.
      */
    public giros.org.Labels.Builder clearLabel() {
      label = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Labels build() {
      try {
        Labels record = new Labels();
        record.label = fieldSetFlags()[0] ? this.label : (java.util.List<giros.org.Label>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Labels>
    WRITER$ = (org.apache.avro.io.DatumWriter<Labels>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Labels>
    READER$ = (org.apache.avro.io.DatumReader<Labels>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.label == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.label.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (giros.org.Label e0: this.label) {
        actualSize0++;
        out.startItem();
        e0.customEncode(out);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.label = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<giros.org.Label> a0 = this.label;
        if (a0 == null) {
          a0 = new SpecificData.Array<giros.org.Label>((int)size0, SCHEMA$.getField("label").schema().getTypes().get(1));
          this.label = a0;
        } else a0.clear();
        SpecificData.Array<giros.org.Label> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<giros.org.Label>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            giros.org.Label e0 = (ga0 != null ? ga0.peek() : null);
            if (e0 == null) {
              e0 = new giros.org.Label();
            }
            e0.customDecode(in);
            a0.add(e0);
          }
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.label = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<giros.org.Label> a0 = this.label;
            if (a0 == null) {
              a0 = new SpecificData.Array<giros.org.Label>((int)size0, SCHEMA$.getField("label").schema().getTypes().get(1));
              this.label = a0;
            } else a0.clear();
            SpecificData.Array<giros.org.Label> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<giros.org.Label>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                giros.org.Label e0 = (ga0 != null ? ga0.peek() : null);
                if (e0 == null) {
                  e0 = new giros.org.Label();
                }
                e0.customDecode(in);
                a0.add(e0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










