version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    network_mode: "host"
    ports:
      - "9090"
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
  collector:
    build:
      context:  ./starlette
    command: /start-reload.sh
    ports:
      - "80:80"
    volumes:
      - ./starlette/app:/app
    
