version: '3'
services:
  app-manager:
    build:
        context: .
        dockerfile: ./docker/app-manager/Dockerfile
    hostname: app-manager
    container_name: app-manager
    environment:
      - APP_MANAGER_URI=${APP_MANAGER_URI}
      - BROKER_URI=${BROKER_URI}
      - CONTEXT_CATALOG_URI=${CONTEXT_CATALOG_URI}
      - FLINK_MANAGER_URI=${FLINK_MANAGER_URI}
      - NIFI_URI=${NIFI_URI}
      - NIFI_USERNAME=${NIFI_USERNAME}
      - NIFI_PASSWORD=${NIFI_PASSWORD}
    ports:
      - "8082:8080"
    volumes:
      - ./docker/app-manager/app_manager:/opt/sda/app-manager/app_manager
    depends_on:
      - nifi
      - scorpio
  ceos1:
    image: "ceos-image:4.25.4M"
    hostname: ceos1
    container_name: ceos1
    ports:
      - "6030:6030"
    command: /sbin/init  systemd.setenv=INTFTYPE=eth systemd.setenv=ETBA=1 systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1 systemd.setenv=CEOS=1 systemd.setenv=EOS_PLATFORM=ceoslab systemd.setenv=container=docker
    privileged: true
    environment:
      INTFTYPE: eth
      ETBA: 1
      SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT: 1
      CEOS: 1
      EOS_PLATFORM: ceoslab
      container: docker
    networks:
      default:
      net1:
      net2:
  ceos2:
    image: "ceos-image:4.25.4M"
    hostname: ceos2
    container_name: ceos2
    ports:
      - "6031:6030"
    command: /sbin/init  systemd.setenv=INTFTYPE=eth systemd.setenv=ETBA=1 systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1 systemd.setenv=CEOS=1 systemd.setenv=EOS_PLATFORM=ceoslab systemd.setenv=container=docker
    privileged: true
    environment:
      INTFTYPE: eth
      ETBA: 1
      SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT: 1
      CEOS: 1
      EOS_PLATFORM: ceoslab
      container: docker
    networks:
      default:
      net1:
      net2:
  consumer:
    build:
      context: .
      dockerfile: ./docker/consumer/Dockerfile
    hostname: consumer
    container_name: consumer
    ports:
      - "8080"
    volumes:
      - ./docker/consumer/consumer:/opt/sda/consumer/consumer
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    ports:
      - "8080"
    volumes:
      - ./docker/context-catalog:/web
  experimenter:
    build:
      context: .
      dockerfile: ./docker/experimenter/Dockerfile
    hostname: experimenter
    container_name: experimenter
    environment:
      - BROKER_URI=${BROKER_URI}
      - CONTEXT_CATALOG_URI=${CONTEXT_CATALOG_URI}
      - EXPERIMENTER_URI=${EXPERIMENTER_URI}
    ports:
      - "8080"
    volumes:
      - ./docker/experimenter/experimenter:/opt/sda/experimenter/experimenter
  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  nifi:
    build:
      context: .
      dockerfile: ./docker/nifi/Dockerfile
    hostname: nifi
    container_name: nifi
    user: root
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      # Must be of 12 characters min
      SINGLE_USER_CREDENTIALS_PASSWORD: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      NIFI_JVM_HEAP_INIT: 4g
      NIFI_JVM_HEAP_MAX: 6g
    ports:
      - "8443:8443"
    volumes:
      - ./gnmi/gnmic-cfgs:/gnmic-cfgs
      - ./docker/nifi:/opt/aggregator
      - ./docker/nifi/drivers/nars:/opt/nifi/nifi-current/extensions
  postgres:
    image: mdillon/postgis
    hostname: postgres
    container_name: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
  scorpio:
    image: scorpiobroker/scorpio:scorpio-aaio_FIWARE_7.9.2
    hostname: scorpio
    container_name: scorpio
    ports:
      - "9090:9090"
    depends_on:
      - kafka
      - postgres
  weaver:
    build:
      context: .
      dockerfile: ./docker/weaver/Dockerfile
    hostname: weaver
    container_name: weaver
    environment:
      - BROKER_URI=${BROKER_URI}
      - CONTEXT_CATALOG_URI=${CONTEXT_CATALOG_URI}
      - FLINK_MANAGER_URI=${FLINK_MANAGER_URI}
      - NIFI_URI=${NIFI_URI}
      - NIFI_USERNAME=${NIFI_USERNAME}
      - NIFI_PASSWORD=${NIFI_PASSWORD}
      - WEAVER_URI=${WEAVER_URI}
    volumes:
      - ./docker/weaver/weaver:/opt/sda/weaver/weaver
    depends_on:
      - nifi
      - scorpio
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none
    working_dir: /
networks:
  net1:
  net2:
