version: '3'
services:
  nifi:
    build:
      context: .
      dockerfile: ./docker/nifi/Dockerfile
    hostname: nifi
    container_name: nifi
    user: root
    environment: 
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      # Must be of 12 characters min
      SINGLE_USER_CREDENTIALS_PASSWORD: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    ports:
      - "8443:8443"
    volumes:
      - ./gnmi/gnmic-cfgs:/gnmic-cfgs
      - ./docker/nifi:/opt/aggregator
      - ./docker/nifi/drivers/nars:/opt/nifi/nifi-current/extensions