version: '3'
services:
  consumer:
    build:
      context: .
      dockerfile: ./docker/consumer/Dockerfile
    hostname: consumer
    container_name: consumer
    ports:
      - "8080"
    volumes:
      - ./docker/consumer/consumer:/opt/sda/consumer/consumer
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    ports:
      - "8080"
    volumes:
      - ./core/context-catalog:/web
  eureka:
    image: scorpiobroker/scorpio:eureka-server_2.1.13
    hostname: eureka
    container_name: eureka
    ports:
      - "8761"
  gateway:
    image: scorpiobroker/scorpio:gateway_aaio_2.1.13
    hostname: gateway
    container_name: gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka
  kafka:
    image: bitnami/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
  postgres:
    image: postgis/postgis
    hostname: postgres
    container_name: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
  scorpio:
    image: scorpiobroker/scorpio:scorpio-aaio_2.1.13
    hostname: scorpio
    container_name: scorpio
    ports:
      - "27015"
    depends_on:
      - gateway
      - eureka
      - postgres
      - kafka
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none
