# generated by datamodel-codegen:
#   filename:  Entity_keyValues.json
#   timestamp: 2020-10-15T18:09:07+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional, Union

from pydantic import AnyUrl, BaseModel, Extra, Field, constr


class Name(BaseModel):
    __root__: constr(
        regex='^((\d|[a-zA-Z]|_)+(:(\d|[a-zA-Z]|_)+)?(#\d+)?)$', min_length=1
    )


class LdContextItem(BaseModel):
    pass


class LdContext(BaseModel):
    __root__: Union[Dict[str, Any], LdContextItem, LdContextItem]


class GeometrySchema(BaseModel):
    pass


class CreatedAt(BaseModel):
    __root__: datetime


class ModifiedAt(BaseModel):
    __root__: datetime


class entity_kv(BaseModel):
    class Config:
        extra = Extra.allow

    id: AnyUrl
    type: Name
    _context: Optional[LdContext] = Field(None, alias='@context')
    location: Optional[GeometrySchema] = None
    observationSpace: Optional[GeometrySchema] = None
    operationSpace: Optional[GeometrySchema] = None
    createdAt: Optional[CreatedAt] = None
    modifiedAt: Optional[ModifiedAt] = None
