apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-detector
spec:
  replicas: 1
  selector:
    matchLabels:
        app: crypto-app
  template:
    metadata:
      labels:
        app: crypto-app
    spec:
      containers:
      - name: crypto-service
        image: kubernetes:31320/crypto-detector:latest
        ports:
        - containerPort: 12000
        args: ["-b", "kafka:9092", "-c", "entrada", "-p", "salida"]
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-service
  labels:
    name: crypto-app
spec:
  ports:
  - name: crypto-port
    port: 12000
    protocol: TCP
  selector:
    app: crypto-app

