# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\tCommonMsg\"\x1f\n\x0eMessageRequest\x12\r\n\x05value\x18\x01 \x01(\t\" \n\x0fMessageResponse\x12\r\n\x05value\x18\x01 \x01(\tb\x06proto3')



_MESSAGEREQUEST = DESCRIPTOR.message_types_by_name['MessageRequest']
_MESSAGERESPONSE = DESCRIPTOR.message_types_by_name['MessageResponse']
MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:CommonMsg.MessageRequest)
  })
_sym_db.RegisterMessage(MessageRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:CommonMsg.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEREQUEST._serialized_start=29
  _MESSAGEREQUEST._serialized_end=60
  _MESSAGERESPONSE._serialized_start=62
  _MESSAGERESPONSE._serialized_end=94
# @@protoc_insertion_point(module_scope)
