# -*- coding: utf-8 -*-
from operator import attrgetter
import pyangbind.lib.xpathhelper as xpathhelper
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType
from pyangbind.lib.yangtypes import RestrictedClassType
from pyangbind.lib.yangtypes import TypedListType
from pyangbind.lib.yangtypes import YANGBool
from pyangbind.lib.yangtypes import YANGListType
from pyangbind.lib.yangtypes import YANGDynClass
from pyangbind.lib.yangtypes import ReferenceType
from pyangbind.lib.base import PybindBase
from collections import OrderedDict
from decimal import Decimal
from bitarray import bitarray
import six

# PY3 support of some PY2 keywords (needs improved)
if six.PY3:
  import builtins as __builtin__
  long = int
elif six.PY2:
  import __builtin__

class yc_so_instantiation_metrics_logparser_instantiation_operation__so_instantiation_metrics(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module logparser-instantiation-operation - based on the path /so-instantiation-metrics. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.

  YANG Description: Enclosing container for the time-related metrics provided by the 5Growth Service Orchestrator related logs during the network service instantiation operation.
  """
  __slots__ = ('_path_helper', '_extmethods', '__current_time','__operation','__nsID','__nsdID','__total_instantiation_time','__SOE_time','__ROE_time','__operation_ID_for_instantiation_op_datetime_difference','__hierarchical_SOE_dispatching_datetime_difference','__ROE_created_VLs_start_datetime_difference','__ROE_retrieve_RL_resources_start_datetime_difference','__ROE_parsing_NSDs_start_datetime_difference','__ROE_updating_DBs_start_datetime_difference','__ROE_extract_VLs_start_datetime_difference','__retrieving_descriptor_from_catalogue_DBs_start_datetime_difference','__PA_calculation_start_datetime_difference','__create_threshold_based_alerts_start_datetime_difference','__create_monitoring_jobs_start_datetime_difference','__create_AIML_alerts_start_datetime_difference','__CoreMANO_wrapper_time',)

  _yang_name = 'so-instantiation-metrics'
  _yang_namespace = 'http://data-aggregator.com/ns/so-log-parser/instantiation-op'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    helper = kwargs.pop("path_helper", None)
    if helper is False:
      self._path_helper = False
    elif helper is not None and isinstance(helper, xpathhelper.YANGPathHelper):
      self._path_helper = helper
    elif hasattr(self, "_parent"):
      helper = getattr(self._parent, "_path_helper", False)
      self._path_helper = helper
    else:
      self._path_helper = False

    self._extmethods = False
    self.__current_time = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={'pattern': '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'}), is_leaf=True, yang_name="current_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='ietf-types:date-and-time', is_config=False)
    self.__operation = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="operation", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)
    self.__nsID = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="nsID", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)
    self.__nsdID = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="nsdID", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)
    self.__total_instantiation_time = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="total_instantiation_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__SOE_time = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="SOE_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__ROE_time = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__operation_ID_for_instantiation_op_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="operation_ID_for_instantiation_op_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__hierarchical_SOE_dispatching_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="hierarchical_SOE_dispatching_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__ROE_created_VLs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_created_VLs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__ROE_retrieve_RL_resources_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_retrieve_RL_resources_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__ROE_parsing_NSDs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_parsing_NSDs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__ROE_updating_DBs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_updating_DBs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__ROE_extract_VLs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_extract_VLs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__retrieving_descriptor_from_catalogue_DBs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="retrieving_descriptor_from_catalogue_DBs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__PA_calculation_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="PA_calculation_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__create_threshold_based_alerts_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_threshold_based_alerts_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__create_monitoring_jobs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_monitoring_jobs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__create_AIML_alerts_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_AIML_alerts_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    self.__CoreMANO_wrapper_time = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="CoreMANO_wrapper_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return ['so-instantiation-metrics']

  def _get_current_time(self):
    """
    Getter method for current_time, mapped from YANG variable /so_instantiation_metrics/current_time (ietf-types:date-and-time)

    YANG Description: Date and time in which the time-related metric values have been sent to Kafka (following the ISO 8601 format).
    """
    return self.__current_time
      
  def _set_current_time(self, v, load=False):
    """
    Setter method for current_time, mapped from YANG variable /so_instantiation_metrics/current_time (ietf-types:date-and-time)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_current_time is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_current_time() directly.

    YANG Description: Date and time in which the time-related metric values have been sent to Kafka (following the ISO 8601 format).
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=six.text_type, restriction_dict={'pattern': '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'}), is_leaf=True, yang_name="current_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='ietf-types:date-and-time', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """current_time must be of a type compatible with ietf-types:date-and-time""",
          'defined-type': "ietf-types:date-and-time",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={'pattern': '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'}), is_leaf=True, yang_name="current_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='ietf-types:date-and-time', is_config=False)""",
        })

    self.__current_time = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_current_time(self):
    self.__current_time = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={'pattern': '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'}), is_leaf=True, yang_name="current_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='ietf-types:date-and-time', is_config=False)


  def _get_operation(self):
    """
    Getter method for operation, mapped from YANG variable /so_instantiation_metrics/operation (string)

    YANG Description: Identifier of the type of operation (i.e., instantiation).
    """
    return self.__operation
      
  def _set_operation(self, v, load=False):
    """
    Setter method for operation, mapped from YANG variable /so_instantiation_metrics/operation (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_operation is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_operation() directly.

    YANG Description: Identifier of the type of operation (i.e., instantiation).
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=six.text_type, is_leaf=True, yang_name="operation", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """operation must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=six.text_type, is_leaf=True, yang_name="operation", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)""",
        })

    self.__operation = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_operation(self):
    self.__operation = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="operation", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)


  def _get_nsID(self):
    """
    Getter method for nsID, mapped from YANG variable /so_instantiation_metrics/nsID (string)

    YANG Description: Network Service Identifier.
    """
    return self.__nsID
      
  def _set_nsID(self, v, load=False):
    """
    Setter method for nsID, mapped from YANG variable /so_instantiation_metrics/nsID (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_nsID is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_nsID() directly.

    YANG Description: Network Service Identifier.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=six.text_type, is_leaf=True, yang_name="nsID", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """nsID must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=six.text_type, is_leaf=True, yang_name="nsID", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)""",
        })

    self.__nsID = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_nsID(self):
    self.__nsID = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="nsID", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)


  def _get_nsdID(self):
    """
    Getter method for nsdID, mapped from YANG variable /so_instantiation_metrics/nsdID (string)

    YANG Description: Network Service Descriptor Identifier.
    """
    return self.__nsdID
      
  def _set_nsdID(self, v, load=False):
    """
    Setter method for nsdID, mapped from YANG variable /so_instantiation_metrics/nsdID (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_nsdID is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_nsdID() directly.

    YANG Description: Network Service Descriptor Identifier.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=six.text_type, is_leaf=True, yang_name="nsdID", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """nsdID must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=six.text_type, is_leaf=True, yang_name="nsdID", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)""",
        })

    self.__nsdID = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_nsdID(self):
    self.__nsdID = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="nsdID", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='string', is_config=False)


  def _get_total_instantiation_time(self):
    """
    Getter method for total_instantiation_time, mapped from YANG variable /so_instantiation_metrics/total_instantiation_time (int64)

    YANG Description: Network service total instantiation time. The time it takes since the 5Gr-SO created the service identifier for a network service until it has been totally instantiated.
    """
    return self.__total_instantiation_time
      
  def _set_total_instantiation_time(self, v, load=False):
    """
    Setter method for total_instantiation_time, mapped from YANG variable /so_instantiation_metrics/total_instantiation_time (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_total_instantiation_time is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_total_instantiation_time() directly.

    YANG Description: Network service total instantiation time. The time it takes since the 5Gr-SO created the service identifier for a network service until it has been totally instantiated.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="total_instantiation_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """total_instantiation_time must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="total_instantiation_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__total_instantiation_time = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_total_instantiation_time(self):
    self.__total_instantiation_time = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="total_instantiation_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_SOE_time(self):
    """
    Getter method for SOE_time, mapped from YANG variable /so_instantiation_metrics/SOE_time (int64)

    YANG Description: Time spent in the Service Orchestration Engine (SOE) module (both at SOE parent, SOE child sub-modules) during the instantiation process.
    """
    return self.__SOE_time
      
  def _set_SOE_time(self, v, load=False):
    """
    Setter method for SOE_time, mapped from YANG variable /so_instantiation_metrics/SOE_time (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_SOE_time is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_SOE_time() directly.

    YANG Description: Time spent in the Service Orchestration Engine (SOE) module (both at SOE parent, SOE child sub-modules) during the instantiation process.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="SOE_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """SOE_time must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="SOE_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__SOE_time = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_SOE_time(self):
    self.__SOE_time = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="SOE_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_ROE_time(self):
    """
    Getter method for ROE_time, mapped from YANG variable /so_instantiation_metrics/ROE_time (int64)

    YANG Description: Time spent in the Resource Orchestration Engine (ROE) module during the instantiation process.
    """
    return self.__ROE_time
      
  def _set_ROE_time(self, v, load=False):
    """
    Setter method for ROE_time, mapped from YANG variable /so_instantiation_metrics/ROE_time (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_ROE_time is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_ROE_time() directly.

    YANG Description: Time spent in the Resource Orchestration Engine (ROE) module during the instantiation process.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """ROE_time must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__ROE_time = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_ROE_time(self):
    self.__ROE_time = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_operation_ID_for_instantiation_op_datetime_difference(self):
    """
    Getter method for operation_ID_for_instantiation_op_datetime_difference, mapped from YANG variable /so_instantiation_metrics/operation_ID_for_instantiation_op_datetime_difference (int64)

    YANG Description: The time it takes the Northbound Interface (NBI) to generate an ID to identify the instantiation operation.
    """
    return self.__operation_ID_for_instantiation_op_datetime_difference
      
  def _set_operation_ID_for_instantiation_op_datetime_difference(self, v, load=False):
    """
    Setter method for operation_ID_for_instantiation_op_datetime_difference, mapped from YANG variable /so_instantiation_metrics/operation_ID_for_instantiation_op_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_operation_ID_for_instantiation_op_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_operation_ID_for_instantiation_op_datetime_difference() directly.

    YANG Description: The time it takes the Northbound Interface (NBI) to generate an ID to identify the instantiation operation.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="operation_ID_for_instantiation_op_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """operation_ID_for_instantiation_op_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="operation_ID_for_instantiation_op_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__operation_ID_for_instantiation_op_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_operation_ID_for_instantiation_op_datetime_difference(self):
    self.__operation_ID_for_instantiation_op_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="operation_ID_for_instantiation_op_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_hierarchical_SOE_dispatching_datetime_difference(self):
    """
    Getter method for hierarchical_SOE_dispatching_datetime_difference, mapped from YANG variable /so_instantiation_metrics/hierarchical_SOE_dispatching_datetime_difference (int64)

    YANG Description: The time the hierarchical Service Orchestration Engine (SOE) uses to select the appropriate instantiation process based on the nature of the service (single NS, composite NS).
    """
    return self.__hierarchical_SOE_dispatching_datetime_difference
      
  def _set_hierarchical_SOE_dispatching_datetime_difference(self, v, load=False):
    """
    Setter method for hierarchical_SOE_dispatching_datetime_difference, mapped from YANG variable /so_instantiation_metrics/hierarchical_SOE_dispatching_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_hierarchical_SOE_dispatching_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_hierarchical_SOE_dispatching_datetime_difference() directly.

    YANG Description: The time the hierarchical Service Orchestration Engine (SOE) uses to select the appropriate instantiation process based on the nature of the service (single NS, composite NS).
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="hierarchical_SOE_dispatching_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """hierarchical_SOE_dispatching_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="hierarchical_SOE_dispatching_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__hierarchical_SOE_dispatching_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_hierarchical_SOE_dispatching_datetime_difference(self):
    self.__hierarchical_SOE_dispatching_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="hierarchical_SOE_dispatching_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_ROE_created_VLs_start_datetime_difference(self):
    """
    Getter method for ROE_created_VLs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_created_VLs_start_datetime_difference (int64)

    YANG Description: Time in the interaction between Resource Orchestration Engine (ROE) and Resource Layer (RL) to allocate resources in the Logical Links (LLs) based on the ROE extract request.
    """
    return self.__ROE_created_VLs_start_datetime_difference
      
  def _set_ROE_created_VLs_start_datetime_difference(self, v, load=False):
    """
    Setter method for ROE_created_VLs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_created_VLs_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_ROE_created_VLs_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_ROE_created_VLs_start_datetime_difference() directly.

    YANG Description: Time in the interaction between Resource Orchestration Engine (ROE) and Resource Layer (RL) to allocate resources in the Logical Links (LLs) based on the ROE extract request.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_created_VLs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """ROE_created_VLs_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_created_VLs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__ROE_created_VLs_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_ROE_created_VLs_start_datetime_difference(self):
    self.__ROE_created_VLs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_created_VLs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_ROE_retrieve_RL_resources_start_datetime_difference(self):
    """
    Getter method for ROE_retrieve_RL_resources_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_retrieve_RL_resources_start_datetime_difference (int64)

    YANG Description: The time to recollect the information from the Resource Layer (RL).
    """
    return self.__ROE_retrieve_RL_resources_start_datetime_difference
      
  def _set_ROE_retrieve_RL_resources_start_datetime_difference(self, v, load=False):
    """
    Setter method for ROE_retrieve_RL_resources_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_retrieve_RL_resources_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_ROE_retrieve_RL_resources_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_ROE_retrieve_RL_resources_start_datetime_difference() directly.

    YANG Description: The time to recollect the information from the Resource Layer (RL).
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_retrieve_RL_resources_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """ROE_retrieve_RL_resources_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_retrieve_RL_resources_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__ROE_retrieve_RL_resources_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_ROE_retrieve_RL_resources_start_datetime_difference(self):
    self.__ROE_retrieve_RL_resources_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_retrieve_RL_resources_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_ROE_parsing_NSDs_start_datetime_difference(self):
    """
    Getter method for ROE_parsing_NSDs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_parsing_NSDs_start_datetime_difference (int64)

    YANG Description: The time at Resource Orchestration Engine (ROE) submodule to parse NSD and VNFDs of an network service to get the required information for Placement Algorithm (PA).
    """
    return self.__ROE_parsing_NSDs_start_datetime_difference
      
  def _set_ROE_parsing_NSDs_start_datetime_difference(self, v, load=False):
    """
    Setter method for ROE_parsing_NSDs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_parsing_NSDs_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_ROE_parsing_NSDs_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_ROE_parsing_NSDs_start_datetime_difference() directly.

    YANG Description: The time at Resource Orchestration Engine (ROE) submodule to parse NSD and VNFDs of an network service to get the required information for Placement Algorithm (PA).
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_parsing_NSDs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """ROE_parsing_NSDs_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_parsing_NSDs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__ROE_parsing_NSDs_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_ROE_parsing_NSDs_start_datetime_difference(self):
    self.__ROE_parsing_NSDs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_parsing_NSDs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_ROE_updating_DBs_start_datetime_difference(self):
    """
    Getter method for ROE_updating_DBs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_updating_DBs_start_datetime_difference (int64)

    YANG Description: Time to update databases (DBs) to declare the network service as operative and the instantiation operation as successful.
    """
    return self.__ROE_updating_DBs_start_datetime_difference
      
  def _set_ROE_updating_DBs_start_datetime_difference(self, v, load=False):
    """
    Setter method for ROE_updating_DBs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_updating_DBs_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_ROE_updating_DBs_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_ROE_updating_DBs_start_datetime_difference() directly.

    YANG Description: Time to update databases (DBs) to declare the network service as operative and the instantiation operation as successful.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_updating_DBs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """ROE_updating_DBs_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_updating_DBs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__ROE_updating_DBs_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_ROE_updating_DBs_start_datetime_difference(self):
    self.__ROE_updating_DBs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_updating_DBs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_ROE_extract_VLs_start_datetime_difference(self):
    """
    Getter method for ROE_extract_VLs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_extract_VLs_start_datetime_difference (int64)

    YANG Description: The time it takes the Resource Orchestration Engine (ROE) to determine the request of the different Virtual Links (VLs) needing resources in the Logical Links (LLs) because
connected VNFs have been deployed in multiple Virtualized Infrastructure Managers (VIMs).
    """
    return self.__ROE_extract_VLs_start_datetime_difference
      
  def _set_ROE_extract_VLs_start_datetime_difference(self, v, load=False):
    """
    Setter method for ROE_extract_VLs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/ROE_extract_VLs_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_ROE_extract_VLs_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_ROE_extract_VLs_start_datetime_difference() directly.

    YANG Description: The time it takes the Resource Orchestration Engine (ROE) to determine the request of the different Virtual Links (VLs) needing resources in the Logical Links (LLs) because
connected VNFs have been deployed in multiple Virtualized Infrastructure Managers (VIMs).
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_extract_VLs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """ROE_extract_VLs_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_extract_VLs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__ROE_extract_VLs_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_ROE_extract_VLs_start_datetime_difference(self):
    self.__ROE_extract_VLs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="ROE_extract_VLs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_retrieving_descriptor_from_catalogue_DBs_start_datetime_difference(self):
    """
    Getter method for retrieving_descriptor_from_catalogue_DBs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/retrieving_descriptor_from_catalogue_DBs_start_datetime_difference (int64)

    YANG Description: The time to collect the descriptor from the network service descriptor (NSD) catalogue.
    """
    return self.__retrieving_descriptor_from_catalogue_DBs_start_datetime_difference
      
  def _set_retrieving_descriptor_from_catalogue_DBs_start_datetime_difference(self, v, load=False):
    """
    Setter method for retrieving_descriptor_from_catalogue_DBs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/retrieving_descriptor_from_catalogue_DBs_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_retrieving_descriptor_from_catalogue_DBs_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_retrieving_descriptor_from_catalogue_DBs_start_datetime_difference() directly.

    YANG Description: The time to collect the descriptor from the network service descriptor (NSD) catalogue.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="retrieving_descriptor_from_catalogue_DBs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """retrieving_descriptor_from_catalogue_DBs_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="retrieving_descriptor_from_catalogue_DBs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__retrieving_descriptor_from_catalogue_DBs_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_retrieving_descriptor_from_catalogue_DBs_start_datetime_difference(self):
    self.__retrieving_descriptor_from_catalogue_DBs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="retrieving_descriptor_from_catalogue_DBs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_PA_calculation_start_datetime_difference(self):
    """
    Getter method for PA_calculation_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/PA_calculation_start_datetime_difference (int64)

    YANG Description: The time to build the request to the Placement Algorithm (PA), send it to the external PA service and receive its answers.
    """
    return self.__PA_calculation_start_datetime_difference
      
  def _set_PA_calculation_start_datetime_difference(self, v, load=False):
    """
    Setter method for PA_calculation_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/PA_calculation_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_PA_calculation_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_PA_calculation_start_datetime_difference() directly.

    YANG Description: The time to build the request to the Placement Algorithm (PA), send it to the external PA service and receive its answers.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="PA_calculation_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """PA_calculation_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="PA_calculation_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__PA_calculation_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_PA_calculation_start_datetime_difference(self):
    self.__PA_calculation_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="PA_calculation_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_create_threshold_based_alerts_start_datetime_difference(self):
    """
    Getter method for create_threshold_based_alerts_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/create_threshold_based_alerts_start_datetime_difference (int64)

    YANG Description: Time interaction between SOE-SLA Manager modules of the 5Gr-SO to determine the threshold-alerts objects (if there is not AI/ML treatment) to be configured at the 5Gr-VoMS
plus the interaction to configure them at the 5GR-VoMs and receive the associated object identifiers and update the information in Network Service Instantiation Resource
(NSIR) database.
    """
    return self.__create_threshold_based_alerts_start_datetime_difference
      
  def _set_create_threshold_based_alerts_start_datetime_difference(self, v, load=False):
    """
    Setter method for create_threshold_based_alerts_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/create_threshold_based_alerts_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_create_threshold_based_alerts_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_create_threshold_based_alerts_start_datetime_difference() directly.

    YANG Description: Time interaction between SOE-SLA Manager modules of the 5Gr-SO to determine the threshold-alerts objects (if there is not AI/ML treatment) to be configured at the 5Gr-VoMS
plus the interaction to configure them at the 5GR-VoMs and receive the associated object identifiers and update the information in Network Service Instantiation Resource
(NSIR) database.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_threshold_based_alerts_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """create_threshold_based_alerts_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_threshold_based_alerts_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__create_threshold_based_alerts_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_create_threshold_based_alerts_start_datetime_difference(self):
    self.__create_threshold_based_alerts_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_threshold_based_alerts_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_create_monitoring_jobs_start_datetime_difference(self):
    """
    Getter method for create_monitoring_jobs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/create_monitoring_jobs_start_datetime_difference (int64)

    YANG Description: Time interaction between SOE-Monitoring Manager modules of 5Gr-SO to determine the monitoring jobs (exporters) and dashboards to be configured at the 5Gr-VoMS plus the interaction
to configure them and receive the associated object identifiers and update the information in Network Service Instantiation Resource (NSIR) database.
    """
    return self.__create_monitoring_jobs_start_datetime_difference
      
  def _set_create_monitoring_jobs_start_datetime_difference(self, v, load=False):
    """
    Setter method for create_monitoring_jobs_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/create_monitoring_jobs_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_create_monitoring_jobs_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_create_monitoring_jobs_start_datetime_difference() directly.

    YANG Description: Time interaction between SOE-Monitoring Manager modules of 5Gr-SO to determine the monitoring jobs (exporters) and dashboards to be configured at the 5Gr-VoMS plus the interaction
to configure them and receive the associated object identifiers and update the information in Network Service Instantiation Resource (NSIR) database.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_monitoring_jobs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """create_monitoring_jobs_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_monitoring_jobs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__create_monitoring_jobs_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_create_monitoring_jobs_start_datetime_difference(self):
    self.__create_monitoring_jobs_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_monitoring_jobs_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_create_AIML_alerts_start_datetime_difference(self):
    """
    Getter method for create_AIML_alerts_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/create_AIML_alerts_start_datetime_difference (int64)

    YANG Description: Time interaction between SOE-SLA Manager to configure the AI/ML workflow to drive scaling operations. The creation and configuration of the data engineering pipeline consist of:
i) interaction with 5Gr-VoMs to create a Kafka Topic, ii) interaction with the 5Gr-AIML platform to download the required model, iii) creation of inference job at Apache Spark,
iv) update of Network Service Instantiation Resource (NSIR) database.
    """
    return self.__create_AIML_alerts_start_datetime_difference
      
  def _set_create_AIML_alerts_start_datetime_difference(self, v, load=False):
    """
    Setter method for create_AIML_alerts_start_datetime_difference, mapped from YANG variable /so_instantiation_metrics/create_AIML_alerts_start_datetime_difference (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_create_AIML_alerts_start_datetime_difference is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_create_AIML_alerts_start_datetime_difference() directly.

    YANG Description: Time interaction between SOE-SLA Manager to configure the AI/ML workflow to drive scaling operations. The creation and configuration of the data engineering pipeline consist of:
i) interaction with 5Gr-VoMs to create a Kafka Topic, ii) interaction with the 5Gr-AIML platform to download the required model, iii) creation of inference job at Apache Spark,
iv) update of Network Service Instantiation Resource (NSIR) database.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_AIML_alerts_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """create_AIML_alerts_start_datetime_difference must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_AIML_alerts_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__create_AIML_alerts_start_datetime_difference = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_create_AIML_alerts_start_datetime_difference(self):
    self.__create_AIML_alerts_start_datetime_difference = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="create_AIML_alerts_start_datetime_difference", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)


  def _get_CoreMANO_wrapper_time(self):
    """
    Getter method for CoreMANO_wrapper_time, mapped from YANG variable /so_instantiation_metrics/CoreMANO_wrapper_time (int64)

    YANG Description: Time spent in the Core MANO Wrapper module during the instantiation process to create virtual network supporting the Virtual Links (VLs), the VMs supporting the VNFs, and
update the Network Service Instantiation Resource (NSIR) database.
    """
    return self.__CoreMANO_wrapper_time
      
  def _set_CoreMANO_wrapper_time(self, v, load=False):
    """
    Setter method for CoreMANO_wrapper_time, mapped from YANG variable /so_instantiation_metrics/CoreMANO_wrapper_time (int64)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_CoreMANO_wrapper_time is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_CoreMANO_wrapper_time() directly.

    YANG Description: Time spent in the Core MANO Wrapper module during the instantiation process to create virtual network supporting the Virtual Links (VLs), the VMs supporting the VNFs, and
update the Network Service Instantiation Resource (NSIR) database.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="CoreMANO_wrapper_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """CoreMANO_wrapper_time must be of a type compatible with int64""",
          'defined-type': "int64",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="CoreMANO_wrapper_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)""",
        })

    self.__CoreMANO_wrapper_time = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_CoreMANO_wrapper_time(self):
    self.__CoreMANO_wrapper_time = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['-9223372036854775808..9223372036854775807']}, int_size=64), is_leaf=True, yang_name="CoreMANO_wrapper_time", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='int64', is_config=False)

  current_time = __builtin__.property(_get_current_time)
  operation = __builtin__.property(_get_operation)
  nsID = __builtin__.property(_get_nsID)
  nsdID = __builtin__.property(_get_nsdID)
  total_instantiation_time = __builtin__.property(_get_total_instantiation_time)
  SOE_time = __builtin__.property(_get_SOE_time)
  ROE_time = __builtin__.property(_get_ROE_time)
  operation_ID_for_instantiation_op_datetime_difference = __builtin__.property(_get_operation_ID_for_instantiation_op_datetime_difference)
  hierarchical_SOE_dispatching_datetime_difference = __builtin__.property(_get_hierarchical_SOE_dispatching_datetime_difference)
  ROE_created_VLs_start_datetime_difference = __builtin__.property(_get_ROE_created_VLs_start_datetime_difference)
  ROE_retrieve_RL_resources_start_datetime_difference = __builtin__.property(_get_ROE_retrieve_RL_resources_start_datetime_difference)
  ROE_parsing_NSDs_start_datetime_difference = __builtin__.property(_get_ROE_parsing_NSDs_start_datetime_difference)
  ROE_updating_DBs_start_datetime_difference = __builtin__.property(_get_ROE_updating_DBs_start_datetime_difference)
  ROE_extract_VLs_start_datetime_difference = __builtin__.property(_get_ROE_extract_VLs_start_datetime_difference)
  retrieving_descriptor_from_catalogue_DBs_start_datetime_difference = __builtin__.property(_get_retrieving_descriptor_from_catalogue_DBs_start_datetime_difference)
  PA_calculation_start_datetime_difference = __builtin__.property(_get_PA_calculation_start_datetime_difference)
  create_threshold_based_alerts_start_datetime_difference = __builtin__.property(_get_create_threshold_based_alerts_start_datetime_difference)
  create_monitoring_jobs_start_datetime_difference = __builtin__.property(_get_create_monitoring_jobs_start_datetime_difference)
  create_AIML_alerts_start_datetime_difference = __builtin__.property(_get_create_AIML_alerts_start_datetime_difference)
  CoreMANO_wrapper_time = __builtin__.property(_get_CoreMANO_wrapper_time)


  _pyangbind_elements = OrderedDict([('current_time', current_time), ('operation', operation), ('nsID', nsID), ('nsdID', nsdID), ('total_instantiation_time', total_instantiation_time), ('SOE_time', SOE_time), ('ROE_time', ROE_time), ('operation_ID_for_instantiation_op_datetime_difference', operation_ID_for_instantiation_op_datetime_difference), ('hierarchical_SOE_dispatching_datetime_difference', hierarchical_SOE_dispatching_datetime_difference), ('ROE_created_VLs_start_datetime_difference', ROE_created_VLs_start_datetime_difference), ('ROE_retrieve_RL_resources_start_datetime_difference', ROE_retrieve_RL_resources_start_datetime_difference), ('ROE_parsing_NSDs_start_datetime_difference', ROE_parsing_NSDs_start_datetime_difference), ('ROE_updating_DBs_start_datetime_difference', ROE_updating_DBs_start_datetime_difference), ('ROE_extract_VLs_start_datetime_difference', ROE_extract_VLs_start_datetime_difference), ('retrieving_descriptor_from_catalogue_DBs_start_datetime_difference', retrieving_descriptor_from_catalogue_DBs_start_datetime_difference), ('PA_calculation_start_datetime_difference', PA_calculation_start_datetime_difference), ('create_threshold_based_alerts_start_datetime_difference', create_threshold_based_alerts_start_datetime_difference), ('create_monitoring_jobs_start_datetime_difference', create_monitoring_jobs_start_datetime_difference), ('create_AIML_alerts_start_datetime_difference', create_AIML_alerts_start_datetime_difference), ('CoreMANO_wrapper_time', CoreMANO_wrapper_time), ])


class logparser_instantiation_operation(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module logparser-instantiation-operation - based on the path /logparser-instantiation-operation. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.

  YANG Description: YANG module to represent the time-related metrics provided by the 5Growth Service Orchestrator (5Gr-SO) Log Management Tool during the network service instantiation operation.
  """
  __slots__ = ('_path_helper', '_extmethods', '__so_instantiation_metrics',)

  _yang_name = 'logparser-instantiation-operation'
  _yang_namespace = 'http://data-aggregator.com/ns/so-log-parser/instantiation-op'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    helper = kwargs.pop("path_helper", None)
    if helper is False:
      self._path_helper = False
    elif helper is not None and isinstance(helper, xpathhelper.YANGPathHelper):
      self._path_helper = helper
    elif hasattr(self, "_parent"):
      helper = getattr(self._parent, "_path_helper", False)
      self._path_helper = helper
    else:
      self._path_helper = False

    self._extmethods = False
    self.__so_instantiation_metrics = YANGDynClass(base=yc_so_instantiation_metrics_logparser_instantiation_operation__so_instantiation_metrics, is_container='container', yang_name="so-instantiation-metrics", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='container', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return []

  def _get_so_instantiation_metrics(self):
    """
    Getter method for so_instantiation_metrics, mapped from YANG variable /so_instantiation_metrics (container)

    YANG Description: Enclosing container for the time-related metrics provided by the 5Growth Service Orchestrator related logs during the network service instantiation operation.
    """
    return self.__so_instantiation_metrics
      
  def _set_so_instantiation_metrics(self, v, load=False):
    """
    Setter method for so_instantiation_metrics, mapped from YANG variable /so_instantiation_metrics (container)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_so_instantiation_metrics is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_so_instantiation_metrics() directly.

    YANG Description: Enclosing container for the time-related metrics provided by the 5Growth Service Orchestrator related logs during the network service instantiation operation.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=yc_so_instantiation_metrics_logparser_instantiation_operation__so_instantiation_metrics, is_container='container', yang_name="so-instantiation-metrics", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='container', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """so_instantiation_metrics must be of a type compatible with container""",
          'defined-type': "container",
          'generated-type': """YANGDynClass(base=yc_so_instantiation_metrics_logparser_instantiation_operation__so_instantiation_metrics, is_container='container', yang_name="so-instantiation-metrics", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='container', is_config=True)""",
        })

    self.__so_instantiation_metrics = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_so_instantiation_metrics(self):
    self.__so_instantiation_metrics = YANGDynClass(base=yc_so_instantiation_metrics_logparser_instantiation_operation__so_instantiation_metrics, is_container='container', yang_name="so-instantiation-metrics", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='http://data-aggregator.com/ns/so-log-parser/instantiation-op', defining_module='logparser-instantiation-operation', yang_type='container', is_config=True)

  so_instantiation_metrics = __builtin__.property(_get_so_instantiation_metrics, _set_so_instantiation_metrics)


  _pyangbind_elements = OrderedDict([('so_instantiation_metrics', so_instantiation_metrics), ])


