# generated by datamodel-codegen:
#   filename:  clarity_data_lake/bucket.json

from __future__ import annotations

from typing import Literal, Optional

from pydantic import Extra, Field, StrictStr

from .. import entity
from ..entity import Entity, Property, Relationship


class BelongsTo(Relationship):
    """
    Relationship. DataLake platform which the bucket belongs to.
    """

    class Config:
        extra = Extra.forbid
        allow_population_by_field_name = True

    object: StrictStr


class CreationDate(Property):
    """
    Property. Date when the bucket was created in the DataLake.
    """

    class Config:
        extra = Extra.forbid
        allow_population_by_field_name = True

    value: entity.DateTime


class Name(Property):
    """
    Property. Name of the bucket.
    """

    class Config:
        extra = Extra.forbid
        allow_population_by_field_name = True

    value: StrictStr


class OwnedBy(Relationship):
    """
    Relationship. AWS S3 owner by whom the bucket is owned.
    """

    class Config:
        extra = Extra.forbid
        allow_population_by_field_name = True

    object: StrictStr


class Bucket(Entity):
    """
    Entity that represents a Bucket in 5G-CLARITY's Data Lake platform.
    """

    class Config:
        extra = Extra.forbid
        allow_population_by_field_name = True

    type: Optional[Literal['Bucket']] = Field(
        'Bucket', description='NGSI-LD Entity identifier. It has to be Bucket'
    )
    belongs_to: BelongsTo = Field(..., alias='belongsTo')
    creation_date: CreationDate = Field(..., alias='creationDate')
    name: Name
    owned_by: OwnedBy = Field(..., alias='ownedBy')
