# generated by datamodel-codegen:
#   filename:  clarity_data_lake/owner.json

from __future__ import annotations

from typing import Literal, Optional

from pydantic import Extra, Field, StrictStr

from ..entity import Entity, Property, Relationship


class MemberOf(Relationship):
    """
    Relationship. DataLake platform of which the owner is member.
    """

    class Config:
        extra = Extra.forbid
        allow_population_by_field_name = True

    object: StrictStr


class OwnerId(Property):
    """
    Property. Owner identifier in AWS.
    """

    class Config:
        extra = Extra.forbid
        allow_population_by_field_name = True

    value: StrictStr


class Owner(Entity):
    """
    Entity that represents an owner in 5G-CLARITY's DataLake platform.
    """

    class Config:
        extra = Extra.forbid
        allow_population_by_field_name = True

    type: Optional[Literal['Owner']] = Field(
        'Owner', description='NGSI-LD Entity identifier. It has to be Owner'
    )
    member_of: Optional[MemberOf] = Field(None, alias='memberOf')
    owner_id: OwnerId = Field(..., alias='ownerId')
