
@startuml

skinparam shadowing false


skinparam ClassHeaderBackgroundColor<<entity>> #f6f688
skinparam ClassBackgroundColor<<entity>> #White
skinparam ClassBorderColor<<entity>> #d4d50f

skinparam ClassHeaderBackgroundColor<<relationship>> #a8e5ad
skinparam ClassBackgroundColor<<relationship>> #White
skinparam ClassBorderColor<<relationship>> #66d270

skinparam ClassFontStyle bold
skinparam ClassFontSize 14
skinparam ClassFontName Helvetica

skinparam ClassStereotypeFontSize 12

skinparam ClassAttributeFontName Helvetica
skinparam ClassAttributeFontSize 12

skinparam nodesep 20
skinparam ranksep 20

skinparam linetype ortho
skinparam ArrowColor #312d2b
skinparam ArrowFontSize 14
skinparam ArrowThickness 1

hide methods
hide <<entity>> circle
hide <<relationship>> circle
show <<entity>> fields

' #######################
' # Definition of classes
' #######################

class Device <<entity>> {
  name
  softwareVersion
  vendor
}

class Module <<entity>> {
  name
  namespace
  revision
}

class implementedBy <<relationship>> {
  feature
  deviation
}

class Protocol <<entity>> {
  address
  port
}

class supportedBy <<relationship>> {
}

class Gnmi <<entity>> {
  encodings
  version
}

class Netconf <<entity>> {
  capabilities
}

class Credentials <<entity>> {
  username
  password
}

class authenticates <<relationship>>{
}

' #######################
' # Draw relationships
' #######################

Device "1..*" --> "1..*" Module
(Device, Module) . implementedBy


'(Credentials, Protocol) . authenticates


@enduml
