# gNMI target address; CLI flag --address
address: "ceos1:6030"
# gNMI target user name; CLI flag --username
username: admin
# gNMI target user password; CLI flag --password
password: xxxx
# Connection mode; CLI flag --insecure
insecure: true

subscriptions:
  # A named subscription, a key is a name
  port_stats:
    # List of subscription paths for that named subscription
    paths:
      - "/interfaces/interface[name=Ethernet1]/state/counters/in-octets"
      - "/interfaces/interface[name=Ethernet1]/state/counters/out-octets"
    # One of [on-change target-defined sample]
    stream-mode: sample
    sample-interval: 5s
    qos: 0

outputs:
  group1:
    - type: prometheus
      # Address to listen on for incoming scape requests
      listen: prometheus:9090
      # Path to query to get the metrics
      path: /metrics
      # Maximum lifetime of metrics in the local cache
      expiration: 60s
      # Enable debug for prometheus output
      debug: false
      # a string to be used as the metric namespace
      metric-prefix: "metric"
      # a boolean, if true the subscription name will be appended to the metric name after the prefix
      append-subscription-name: true

