"""
    ETSI ISG CIM / NGSI-LD API

    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders  # noqa: E501

    The version of the OpenAPI document: latest
    Contact: NGSI-LD@etsi.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.geometry import Geometry
from openapi_client.model.ld_context import LdContext
from openapi_client.model.registration_info import RegistrationInfo
from openapi_client.model.time_interval import TimeInterval
globals()['Geometry'] = Geometry
globals()['LdContext'] = LdContext
globals()['RegistrationInfo'] = RegistrationInfo
globals()['TimeInterval'] = TimeInterval
from openapi_client.model.context_source_registration_fragment import ContextSourceRegistrationFragment


class TestContextSourceRegistrationFragment(unittest.TestCase):
    """ContextSourceRegistrationFragment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContextSourceRegistrationFragment(self):
        """Test ContextSourceRegistrationFragment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContextSourceRegistrationFragment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
