"""
    ETSI ISG CIM / NGSI-LD API

    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders  # noqa: E501

    The version of the OpenAPI document: latest
    Contact: NGSI-LD@etsi.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.line_string import LineString


class TestLineString(unittest.TestCase):
    """LineString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLineString(self):
        """Test LineString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LineString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
