---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goflow2
  labels:
    app: goflow2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goflow2
  template:
    metadata:
      labels:
        app: goflow2
    spec:
      containers:
        - args:
            - -transport=kafka
            - -transport.kafka.brokers=kafka-service:9092
            - -transport.kafka.topic=flows
            - -format=json
            - -listen=netflow://:9995
          image: kubernetes:31320/goflow2:latest
          name: goflow2
          ports:
            - containerPort: 9995
              protocol: UDP
      hostname: goflow2
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: goflow2
  labels:
    app: goflow2
spec:
  ports:
    - name: client
      port: 9995
      protocol: UDP
      targetPort: 9995
  selector:
    app: goflow2
