apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorapp-module
  labels:
    app: statefun
data:
  module.yaml: |+
    kind: io.statefun.endpoints.v2/http
    spec:
      functions: normfuncs/aggregatorApp
      urlPathTemplate: http://aggregatorapp-python:8060/statefun
    ---
    kind: io.statefun.kafka.v1/ingress
    spec:
      id: tidtopics/my-ingress
      address: kafka:9092
      consumerGroupId: tidtopics
      topics:
        - topic: raw
          valueType: io.statefun.types/string
          targets:
            - normfuncs/aggregatorApp
    ---
    kind: io.statefun.kafka.v1/egress
    spec:
      id: tidtopics/my-egress
      address: kafka:9092
      deliverySemantic:
        type: exactly-once
        transactionTimeout: 15min
