"""
    ETSI ISG CIM / NGSI-LD API

    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders  # noqa: E501

    The version of the OpenAPI document: latest
    Contact: NGSI-LD@etsi.org
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.context_source_registration import ContextSourceRegistration
from openapi_client.model.context_source_registration_list import ContextSourceRegistrationList
from openapi_client.model.coordinates import Coordinates
from openapi_client.model.geometry import Geometry
from openapi_client.model.georel import Georel
from openapi_client.model.problem_details import ProblemDetails


class CSourceRegistrationsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.query_csources_endpoint = _Endpoint(
            settings={
                'response_type': (ContextSourceRegistrationList,),
                'auth': [],
                'endpoint_path': '/csourceRegistrations/',
                'operation_id': 'query_csources',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                    'id_pattern',
                    'type',
                    'attrs',
                    'q',
                    'georel',
                    'geometry',
                    'coordinates',
                    'geoproperty',
                    'limit',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'type',
                    'attrs',
                    'q',
                    'geoproperty',
                    'limit',
                ]
            },
            root_map={
                'validations': {
                    ('type',): {

                        'min_length': 1,
                    },
                    ('attrs',): {

                        'min_length': 1,
                    },
                    ('q',): {

                        'min_length': 1,
                    },
                    ('geoproperty',): {

                        'min_length': 1,
                    },
                    ('limit',): {

                        'inclusive_minimum': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'id_pattern':
                        (str,),
                    'type':
                        (str,),
                    'attrs':
                        (str,),
                    'q':
                        (str,),
                    'georel':
                        (Georel,),
                    'geometry':
                        (Geometry,),
                    'coordinates':
                        (Coordinates,),
                    'geoproperty':
                        (str,),
                    'limit':
                        (int,),
                },
                'attribute_map': {
                    'id': 'id',
                    'id_pattern': 'idPattern',
                    'type': 'type',
                    'attrs': 'attrs',
                    'q': 'q',
                    'georel': 'georel',
                    'geometry': 'geometry',
                    'coordinates': 'coordinates',
                    'geoproperty': 'geoproperty',
                    'limit': 'limit',
                },
                'location_map': {
                    'id': 'query',
                    'id_pattern': 'query',
                    'type': 'query',
                    'attrs': 'query',
                    'q': 'query',
                    'georel': 'query',
                    'geometry': 'query',
                    'coordinates': 'query',
                    'geoproperty': 'query',
                    'limit': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json;application/ld+json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.register_csource_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [],
                'endpoint_path': '/csourceRegistrations/',
                'operation_id': 'register_csource',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'context_source_registration',
                ],
                'required': [
                    'context_source_registration',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'context_source_registration':
                        (ContextSourceRegistration,),
                },
                'attribute_map': {
                },
                'location_map': {
                    'context_source_registration': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json;application/ld+json'
                ],
                'content_type': [
                    'application/json;application/ld+json'
                ]
            },
            api_client=api_client
        )
        self.remove_csource_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [],
                'endpoint_path': '/csourceRegistrations/{registrationId}',
                'operation_id': 'remove_csource',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'registration_id',
                ],
                'required': [
                    'registration_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'registration_id':
                        (str,),
                },
                'attribute_map': {
                    'registration_id': 'registrationId',
                },
                'location_map': {
                    'registration_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json;application/ld+json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.retrieve_csource_endpoint = _Endpoint(
            settings={
                'response_type': (ContextSourceRegistration,),
                'auth': [],
                'endpoint_path': '/csourceRegistrations/{registrationId}',
                'operation_id': 'retrieve_csource',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'registration_id',
                ],
                'required': [
                    'registration_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'registration_id':
                        (str,),
                },
                'attribute_map': {
                    'registration_id': 'registrationId',
                },
                'location_map': {
                    'registration_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json;application/ld+json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )

    def query_csources(
        self,
        **kwargs
    ):
        """query_csources  # noqa: E501

        Retrieve a set of context sources which matches a specific query from an NGSI-LD system  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.query_csources(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            id (str): Comma separated list of URIs to be retrieved. [optional]
            id_pattern (str): Regular expression that must be matched by Entity ids. [optional]
            type (str): Comma separated list of Entity type names to be retrieved. [optional]
            attrs (str): Comma separated list of attribute names (properties or relationships) to be retrieved. [optional]
            q (str): Query. [optional]
            georel (Georel): Geo-relationship. [optional]
            geometry (Geometry): Geometry. [optional]
            coordinates (Coordinates): Coordinates serialized as a string. [optional]
            geoproperty (str): The name of the property that contains the geo-spatial data that will be used to resolve the geoquery. [optional]
            limit (int): Pagination limit. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            ContextSourceRegistrationList
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_host_index'] = kwargs.get('_host_index')
        return self.query_csources_endpoint.call_with_http_info(**kwargs)

    def register_csource(
        self,
        context_source_registration,
        **kwargs
    ):
        """register_csource  # noqa: E501

        Registers a new context source within an NGSI-LD system  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.register_csource(context_source_registration, async_req=True)
        >>> result = thread.get()

        Args:
            context_source_registration (ContextSourceRegistration):

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['context_source_registration'] = \
            context_source_registration
        return self.register_csource_endpoint.call_with_http_info(**kwargs)

    def remove_csource(
        self,
        registration_id,
        **kwargs
    ):
        """remove_csource  # noqa: E501

        Removes an specific context source registration within an NGSI-LD system  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.remove_csource(registration_id, async_req=True)
        >>> result = thread.get()

        Args:
            registration_id (str): Registration Id

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['registration_id'] = \
            registration_id
        return self.remove_csource_endpoint.call_with_http_info(**kwargs)

    def retrieve_csource(
        self,
        registration_id,
        **kwargs
    ):
        """retrieve_csource  # noqa: E501

        Retrieves a specific context source registration from an NGSI-LD system  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.retrieve_csource(registration_id, async_req=True)
        >>> result = thread.get()

        Args:
            registration_id (str): Registration Id

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            ContextSourceRegistration
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['registration_id'] = \
            registration_id
        return self.retrieve_csource_endpoint.call_with_http_info(**kwargs)

