apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorapp-module
  labels:
    app: statefun
data:
  module.yaml: |+
    kind: io.statefun.endpoints.v2/http
    spec:
      functions: {{ .Values.module.functions }}
      urlPathTemplate: {{ .Values.module.url_path_template }}
    ---
    kind: io.statefun.kafka.v1/ingress
    spec:
      id: tidtopics/my-ingress
      address: {{ .Values.module.kafka_address }}
      consumerGroupId: tidtopics
      topics:
        - topic: raw
          valueType: io.statefun.types/string
          targets:
            - {{ .Values.module.functions }}
    ---
    kind: io.statefun.kafka.v1/egress
    spec:
      id: tidtopics/my-egress
      address: {{ .Values.module.kafka_address }}
      deliverySemantic:
        type: exactly-once
        transactionTimeout: 15min
