apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-producer
spec:
  replicas: 1
  selector:
    matchLabels:
        app: crypto-producer-app
  template:
    metadata:
      labels:
        app: crypto-producer-app
    spec:
      containers:
      - name: crypto-producer-service
        image: <k8s-registry-ip>:<k8s-registry-port>/crypto-producer:latest
        ports:
        - containerPort: 12001
        args: ["-b", "kafka:9092", "-p", "sda-netflow-dcp", "-t", "1"]
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-producer-service
  labels:
    name: crypto-producer-app
spec:
  ports:
  - name: crypto-producer-port
    port: 12001
    protocol: TCP
  selector:
    app: crypto-producer-app
