apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-detector
spec:
  replicas: 1
  selector:
    matchLabels:
        app: crypto-detector-app
  template:
    metadata:
      labels:
        app: crypto-detector-app
    spec:
      containers:
      - name: crypto-detector-service
        image: <k8s-registry-ip>:<k8s-registry-port>/crypto-detector:latest
        ports:
        - containerPort: 12000
        args: ["-b", "kafka:9092", "-c", "sda-netflow-dcp", "-p", "sda-netflow-cds"]
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-detector-service
  labels:
    name: crypto-detector-app
spec:
  ports:
  - name: crypto-detector-port
    port: 12000
    protocol: TCP
  selector:
    app: crypto-detector-app

