/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package giros.org;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EveRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7414981684613172354L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EveRecord\",\"namespace\":\"giros.org\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"string\",\"doc\":\"/eve-record/timestamp\",\"logicalType\":\"local-timestamp-millis\"},{\"name\":\"value\",\"type\":\"double\",\"doc\":\"/eve-record/value\",\"logicalType\":\"decimal\",\"precision\":\"6\"},{\"name\":\"unit\",\"type\":\"string\",\"doc\":\"/eve-record/unit\"},{\"name\":\"device_id\",\"type\":[\"null\",\"string\"],\"doc\":\"/eve-record/device-id\",\"aliases\":[\"device-id\"]},{\"name\":\"labels\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Labels\",\"fields\":[{\"name\":\"label\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Label\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"doc\":\"/eve-record/labels/label/name\"},{\"name\":\"value\",\"type\":\"string\",\"doc\":\"/eve-record/labels/label/value\"}],\"aliases\":[\"labelType\"]}}],\"doc\":\"/eve-record/labels/label\"}],\"aliases\":[\"labelsType\"]}],\"doc\":\"/eve-record/labels\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EveRecord> ENCODER =
      new BinaryMessageEncoder<EveRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EveRecord> DECODER =
      new BinaryMessageDecoder<EveRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EveRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EveRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EveRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EveRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EveRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EveRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EveRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EveRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** /eve-record/timestamp */
   private java.lang.CharSequence timestamp;
  /** /eve-record/value */
   private double value;
  /** /eve-record/unit */
   private java.lang.CharSequence unit;
  /** /eve-record/device-id */
   private java.lang.CharSequence device_id;
  /** /eve-record/labels */
   private giros.org.Labels labels;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EveRecord() {}

  /**
   * All-args constructor.
   * @param timestamp /eve-record/timestamp
   * @param value /eve-record/value
   * @param unit /eve-record/unit
   * @param device_id /eve-record/device-id
   * @param labels /eve-record/labels
   */
  public EveRecord(java.lang.CharSequence timestamp, java.lang.Double value, java.lang.CharSequence unit, java.lang.CharSequence device_id, giros.org.Labels labels) {
    this.timestamp = timestamp;
    this.value = value;
    this.unit = unit;
    this.device_id = device_id;
    this.labels = labels;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return timestamp;
    case 1: return value;
    case 2: return unit;
    case 3: return device_id;
    case 4: return labels;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: timestamp = (java.lang.CharSequence)value$; break;
    case 1: value = (java.lang.Double)value$; break;
    case 2: unit = (java.lang.CharSequence)value$; break;
    case 3: device_id = (java.lang.CharSequence)value$; break;
    case 4: labels = (giros.org.Labels)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return /eve-record/timestamp
   */
  public java.lang.CharSequence getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * /eve-record/timestamp
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.CharSequence value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return /eve-record/value
   */
  public double getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * /eve-record/value
   * @param value the value to set.
   */
  public void setValue(double value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'unit' field.
   * @return /eve-record/unit
   */
  public java.lang.CharSequence getUnit() {
    return unit;
  }


  /**
   * Sets the value of the 'unit' field.
   * /eve-record/unit
   * @param value the value to set.
   */
  public void setUnit(java.lang.CharSequence value) {
    this.unit = value;
  }

  /**
   * Gets the value of the 'device_id' field.
   * @return /eve-record/device-id
   */
  public java.lang.CharSequence getDeviceId() {
    return device_id;
  }


  /**
   * Sets the value of the 'device_id' field.
   * /eve-record/device-id
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.CharSequence value) {
    this.device_id = value;
  }

  /**
   * Gets the value of the 'labels' field.
   * @return /eve-record/labels
   */
  public giros.org.Labels getLabels() {
    return labels;
  }


  /**
   * Sets the value of the 'labels' field.
   * /eve-record/labels
   * @param value the value to set.
   */
  public void setLabels(giros.org.Labels value) {
    this.labels = value;
  }

  /**
   * Creates a new EveRecord RecordBuilder.
   * @return A new EveRecord RecordBuilder
   */
  public static giros.org.EveRecord.Builder newBuilder() {
    return new giros.org.EveRecord.Builder();
  }

  /**
   * Creates a new EveRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EveRecord RecordBuilder
   */
  public static giros.org.EveRecord.Builder newBuilder(giros.org.EveRecord.Builder other) {
    if (other == null) {
      return new giros.org.EveRecord.Builder();
    } else {
      return new giros.org.EveRecord.Builder(other);
    }
  }

  /**
   * Creates a new EveRecord RecordBuilder by copying an existing EveRecord instance.
   * @param other The existing instance to copy.
   * @return A new EveRecord RecordBuilder
   */
  public static giros.org.EveRecord.Builder newBuilder(giros.org.EveRecord other) {
    if (other == null) {
      return new giros.org.EveRecord.Builder();
    } else {
      return new giros.org.EveRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for EveRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EveRecord>
    implements org.apache.avro.data.RecordBuilder<EveRecord> {

    /** /eve-record/timestamp */
    private java.lang.CharSequence timestamp;
    /** /eve-record/value */
    private double value;
    /** /eve-record/unit */
    private java.lang.CharSequence unit;
    /** /eve-record/device-id */
    private java.lang.CharSequence device_id;
    /** /eve-record/labels */
    private giros.org.Labels labels;
    private giros.org.Labels.Builder labelsBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(giros.org.EveRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.unit)) {
        this.unit = data().deepCopy(fields()[2].schema(), other.unit);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.device_id)) {
        this.device_id = data().deepCopy(fields()[3].schema(), other.device_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.labels)) {
        this.labels = data().deepCopy(fields()[4].schema(), other.labels);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasLabelsBuilder()) {
        this.labelsBuilder = giros.org.Labels.newBuilder(other.getLabelsBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing EveRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(giros.org.EveRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.unit)) {
        this.unit = data().deepCopy(fields()[2].schema(), other.unit);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.device_id)) {
        this.device_id = data().deepCopy(fields()[3].schema(), other.device_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.labels)) {
        this.labels = data().deepCopy(fields()[4].schema(), other.labels);
        fieldSetFlags()[4] = true;
      }
      this.labelsBuilder = null;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * /eve-record/timestamp
      * @return The value.
      */
    public java.lang.CharSequence getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * /eve-record/timestamp
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public giros.org.EveRecord.Builder setTimestamp(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.timestamp = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * /eve-record/timestamp
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * /eve-record/timestamp
      * @return This builder.
      */
    public giros.org.EveRecord.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * /eve-record/value
      * @return The value.
      */
    public double getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * /eve-record/value
      * @param value The value of 'value'.
      * @return This builder.
      */
    public giros.org.EveRecord.Builder setValue(double value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * /eve-record/value
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * /eve-record/value
      * @return This builder.
      */
    public giros.org.EveRecord.Builder clearValue() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'unit' field.
      * /eve-record/unit
      * @return The value.
      */
    public java.lang.CharSequence getUnit() {
      return unit;
    }


    /**
      * Sets the value of the 'unit' field.
      * /eve-record/unit
      * @param value The value of 'unit'.
      * @return This builder.
      */
    public giros.org.EveRecord.Builder setUnit(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.unit = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'unit' field has been set.
      * /eve-record/unit
      * @return True if the 'unit' field has been set, false otherwise.
      */
    public boolean hasUnit() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'unit' field.
      * /eve-record/unit
      * @return This builder.
      */
    public giros.org.EveRecord.Builder clearUnit() {
      unit = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'device_id' field.
      * /eve-record/device-id
      * @return The value.
      */
    public java.lang.CharSequence getDeviceId() {
      return device_id;
    }


    /**
      * Sets the value of the 'device_id' field.
      * /eve-record/device-id
      * @param value The value of 'device_id'.
      * @return This builder.
      */
    public giros.org.EveRecord.Builder setDeviceId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.device_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'device_id' field has been set.
      * /eve-record/device-id
      * @return True if the 'device_id' field has been set, false otherwise.
      */
    public boolean hasDeviceId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'device_id' field.
      * /eve-record/device-id
      * @return This builder.
      */
    public giros.org.EveRecord.Builder clearDeviceId() {
      device_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'labels' field.
      * /eve-record/labels
      * @return The value.
      */
    public giros.org.Labels getLabels() {
      return labels;
    }


    /**
      * Sets the value of the 'labels' field.
      * /eve-record/labels
      * @param value The value of 'labels'.
      * @return This builder.
      */
    public giros.org.EveRecord.Builder setLabels(giros.org.Labels value) {
      validate(fields()[4], value);
      this.labelsBuilder = null;
      this.labels = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'labels' field has been set.
      * /eve-record/labels
      * @return True if the 'labels' field has been set, false otherwise.
      */
    public boolean hasLabels() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'labels' field and creates one if it doesn't exist yet.
     * /eve-record/labels
     * @return This builder.
     */
    public giros.org.Labels.Builder getLabelsBuilder() {
      if (labelsBuilder == null) {
        if (hasLabels()) {
          setLabelsBuilder(giros.org.Labels.newBuilder(labels));
        } else {
          setLabelsBuilder(giros.org.Labels.newBuilder());
        }
      }
      return labelsBuilder;
    }

    /**
     * Sets the Builder instance for the 'labels' field
     * /eve-record/labels
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public giros.org.EveRecord.Builder setLabelsBuilder(giros.org.Labels.Builder value) {
      clearLabels();
      labelsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'labels' field has an active Builder instance
     * /eve-record/labels
     * @return True if the 'labels' field has an active Builder instance
     */
    public boolean hasLabelsBuilder() {
      return labelsBuilder != null;
    }

    /**
      * Clears the value of the 'labels' field.
      * /eve-record/labels
      * @return This builder.
      */
    public giros.org.EveRecord.Builder clearLabels() {
      labels = null;
      labelsBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EveRecord build() {
      try {
        EveRecord record = new EveRecord();
        record.timestamp = fieldSetFlags()[0] ? this.timestamp : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.Double) defaultValue(fields()[1]);
        record.unit = fieldSetFlags()[2] ? this.unit : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.device_id = fieldSetFlags()[3] ? this.device_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (labelsBuilder != null) {
          try {
            record.labels = this.labelsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("labels"));
            throw e;
          }
        } else {
          record.labels = fieldSetFlags()[4] ? this.labels : (giros.org.Labels) defaultValue(fields()[4]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EveRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<EveRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EveRecord>
    READER$ = (org.apache.avro.io.DatumReader<EveRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.timestamp);

    out.writeDouble(this.value);

    out.writeString(this.unit);

    if (this.device_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.device_id);
    }

    if (this.labels == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.labels.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.timestamp = in.readString(this.timestamp instanceof Utf8 ? (Utf8)this.timestamp : null);

      this.value = in.readDouble();

      this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.device_id = null;
      } else {
        this.device_id = in.readString(this.device_id instanceof Utf8 ? (Utf8)this.device_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.labels = null;
      } else {
        if (this.labels == null) {
          this.labels = new giros.org.Labels();
        }
        this.labels.customDecode(in);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.timestamp = in.readString(this.timestamp instanceof Utf8 ? (Utf8)this.timestamp : null);
          break;

        case 1:
          this.value = in.readDouble();
          break;

        case 2:
          this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.device_id = null;
          } else {
            this.device_id = in.readString(this.device_id instanceof Utf8 ? (Utf8)this.device_id : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.labels = null;
          } else {
            if (this.labels == null) {
              this.labels = new giros.org.Labels();
            }
            this.labels.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










